name: tavern_simple
dependencies:
  browser: any
  tavern:
    path: ../../
transformers:
- tavern:
    site_url: "http://example.com/"
    sitemap_path: "/sitemap.xml"
    tag_page_index: "/tags/index.html"
